version: '3.9'
services:
  api:
    build: .
    container_name: spoeq-api
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:7
    container_name: spoeq-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
